import React, { useState, useEffect } from "react";import './registration.css';
import GroupRegistrationForm from "../../componant/Student/grpRegForm";

function Registration() {
  
    const [showAddPannelModal, setShowAddPannelModal] = useState(false);
  

  function toggleContent(event) {
    // Find the parent element of the button
    const parentElement = event.target.closest(".registration-section-head");
    
    // Find the content associated with the parent element
    const content = parentElement.nextElementSibling;
    
    // Toggle the display of the content
    if (content.style.display === "none" || content.style.display === "") {
      content.style.display = "block";
      event.target.innerHTML = "-";
    } else {
      content.style.display = "none";
      event.target.innerHTML = "+";
    }
  }
  function toggleContent2(event2) {
    // Find the parent element of the button
    const parentElement2 = event2.target.closest(".research-publicaton-head");
    
    // Find the content associated with the parent element
    const research = parentElement2.nextElementSibling;
    
    // Toggle the display of the content
    if (research.style.display === "none" || research.style.display === "") {
      research.style.display = "block";
      event2.target.innerHTML = "-";
    } else {
      research.style.display = "none";
      event2.target.innerHTML = "+";
    }
  }

  return (
    <div className="registration-container">
      <div className="horizontal-line"></div>
      <header className="registration-header">
        <div className="registration-title-container">
          <img className="registration-logo" src="logo.svg" alt="User" />
        </div>
      </header>
      <main className="registration-main">
        <section className="staff-members">
          <h2>Staff members to contact regarding inquiries related to the module:</h2>
          <p>Ms. Virajini (virajini.g@sliit.lk) – For any assessment-related inquiries or issues</p>
          <p>Ms. Poojani (poojani.g@sliit.lk) – For inquiries about group formation or submission of group details</p>
          <p>Dr. Dilshan (dilshan.i@sliit.lk) – For any concerns about the final examination paper</p>
        </section>
        <section className="email-guidelines">
          <h2>Notice: Sending emails to staff members</h2>
          <p>When sending emails to staff members, please adhere to the following guidelines:</p>
          <p>Send emails from your SLIIT account. Emails sent from other accounts will not receive a response.</p>
          <p>Ensure that you mention the module name and project group number.</p>
          <p>Only send the email to the relevant staff member.</p>
          <p>Refrain from copying emails sent to one staff member to other module members.</p>
          <p>Avoid sending the same email as separate emails to multiple staff members.</p>
          <p>When communicating your message, refrain from sending lengthy emails generated by AI tools. Instead, concisely state your concerns directly.</p>
        </section>
        <br></br>
            <br></br>
            <br></br>
        <section className="registration-sections">
          <section className="assessments-section">
            <h1>ASSESMENTS</h1>
          </section>
          <br></br>
          <article className="registration-section1">
            <article className="registration-section-head">
              <h3>GROUP REGISTRATION</h3>
              <button onClick={toggleContent}>+</button>
            </article>
            <p className="content" style={{ display: 'none' }}><br></br>NOTICE <br></br> If you notice any errors or if your group information is not included, send an email to itpm.it3040@gmail.com before February 17, 2024.

For groups listed under the "No Sub" sheet, it is mandatory to specify their assigned lab group in Column G next to each student before February 17, 2024.

Kindly note that no teams have been allocated a team number for the ITPM module yet. <br></br>Register using form below <br></br> 
<br></br>
<button onClick={() => setShowAddPannelModal(true)} className="Russa_PresentationPannelTable_addNew">
         
          Register Here </button></p>
           
          </article>
          <br></br>
          <article className="registration-section2">
            <h3>ASSESMENT 1</h3>
            <button onClick={toggleContent}>+</button>
          </article>
          <br></br>
          <article className="registration-section3">
            <h3>ASSESMENT 2</h3>
            <button onClick={toggleContent}>+</button>
          </article>
        </section>
<br></br>
        <article className="research-publicaton-head">
          <h2>RESEARCH PUBLICATION</h2>
          <button onClick={toggleContent2}>+</button>
          </article>
          
            <p className="research" style={{ display: 'none' }}><br></br>NOTICE <br></br> If you notice any errors or if your group information is not included, send an email to itpm.it3040@gmail.com before February 17, 2024.

For groups listed under the "No Sub" sheet, it is mandatory to specify their assigned lab group in Column G next to each student before February 17, 2024.

Kindly note that no teams have been allocated a team number for the ITPM module yet. <br></br>Register using form below </p>
           
<br></br>
            <br></br>
            <br></br>
          <article className="semester-mark">
            <h3>SEMESTER MARKS</h3> 
            </article>
            <br></br>
            <article className="semester-mark-head">
              <h3>PRESENTATION 1 MARK</h3>
              <button onClick={toggleContent}>+</button>
            </article>
            <br></br>
            <article className="semester-mark-head">
              <h3>PRESENTATION 2 MARK</h3>
              <button onClick={toggleContent}>+</button>
            </article>
            <br></br>
            <article className="semester-mark-head">
              <h3>PRESENTATION 3 MARK</h3>
              <button onClick={toggleContent}>+</button>
            </article>
         
        
      </main>
      {showAddPannelModal && <GroupRegistrationForm onClose={() => { setShowAddPannelModal(false) }} />}
    </div>
  );
}

export default Registration;

